name: PR review workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: 'PR review'
        run: 'echo "this was triggered from a PR review"'
        shell: pwsh
      - name: 'Create internal branch'
        # todo: if comment == 'lgtm' && branch is from fork
        uses: ./../actions/create-internal-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}