name: PR workflow

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  job1:
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
      RUN_PUBLISH_STEPS: ${{ secrets.secret_1 != '' }}
    steps:
      - name: '[DEBUG] Echo environment variables'
        run: 'gci Env:'
        shell: pwsh