name: Secret test

on:
  pull_request:
    types: 
      - opened
  pull_request_review:
    types:
      - submitted

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: 'Echo secret'
        run: 'echo "Secret is: ${{ secrets.secret_1 }}'